import NavBar from "../components/NavBar"
import './global.css'
import Header from '../components/Header'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import "./page.module.css"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* You can include metadata or link tags here */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>

      <body className="bodyStyle">
          <div className='children'>
            {children}
          </div>
      </body>
    </html>
  )
}
